
# Configuración básica de conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BibliotecaDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Opcional: pool de conexiones
spring.sql.init.mode=always

# Para pruebas: mostrar consultas SQL en consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# Puerto del servidor (puedes cambiarlo si deseas)

server.port=8080
